### ISSUE TITLE
Correct License Badge

### ISSUE THREAD

**Issue by iancnorden** [berzerk0/Probable-Wordlists#11]
Currently doesn't handle a click through to the 4.0 license, instead goes to image.

As you are using CC 4.0 by SA try:
License: CC BY-SA 4.0
[![License: CC BY-SA 4.0](https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg)](http://creativecommons.org/licenses/by-sa/4.0/)

Reference: https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba

**Comment by iancnorden** [comment]
Would also suggest a proper license file and reference to license, instead of a README.md markup addition as you have. Use https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt plaintext format to build a license file to push into the repo.

Reference list: https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/

**Comment by berzerk0** [comment]
A++ QC
