### ISSUE TITLE
Mix of line endings

### ISSUE THREAD

**Issue by magnumripper** [berzerk0/Probable-Wordlists#14]
It seems to me everything under Dictionary-Style has CRLF line endings. IMHO every file should have LF endings, so people don't end up with a *mix* of line endings after concatenating files.

**Comment by berzerk0** [comment]
Good catch, on it.

**Comment by berzerk0** [comment]
This will be fixed in 1.2

**Comment by berzerk0** [comment]
Files with cleaned up line endings available in Megalinks now.
Same files will be in torrents.
