### ISSUE TITLE
Please make torrents easier to find

### ISSUE THREAD

**Issue by jonathancross** [berzerk0/Probable-Wordlists#17]
I believe you would get more seeders if [Release notes](/berzerk0/Probable-Wordlists/releases) explicitly linked to each torrent file (so potential seeders could just click each link).

Also, the main README says "**Torrents are live!**"  but nothing more.  Instead you might say:

> Torrents are live -- **[please us help seed these files](/berzerk0/Probable-Wordlists/releases)**!

**Comment by berzerk0** [comment]
Good thinking - I'll do it now

**Comment by berzerk0** [comment]
Added links - they can now be seen directly from the landing page.

Good thinking, @jonathancross

**Comment by jonathancross** [comment]
Great, thanks!
