### ISSUE TITLE
De-duplicate items

### ISSUE THREAD

**Issue by Miserlou** [berzerk0/Probable-Wordlists#2]
#Looks like there could be quite a few dupes in here, for instance, "password" is at 1 and 19: https://github.com/berzerk0/Probable-Wordlists/blob/master/Real-Passwords/WPA-Length/Top76-probable-WPA.txt

**Comment by Miserlou** [comment]
Good project though!

Would love to see a list of WPA-formatted passwords that come _just_ from router/wifi sources, not user-passwords.

**Comment by berzerk0** [comment]
So this is me getting caught with the classic invisible newline between windows and Linux. 
Rev 1.1 will have this fixed in the main files, the Chunk files will take longer.

**Comment by WiseNerd** [comment]
Easy fix for the dupes could be running :%s^M\+ in vim to kill the trailing blank space artifacts from windows, and then issuing uniq -u passfile.txt > cleanpassfile.txt

**Comment by blobgo** [comment]
@WiseNerd So if you already fixed it, why not make a PR?

**Comment by iancnorden** [comment]
PR from me shortly for de-dupe. Great work.

**Comment by berzerk0** [comment]
@iancnorden You're gonna beat me to the punch! 
I have the desktop chugging away, but won't be back to upload changes for a half day or so

**Comment by iancnorden** [comment]
Now it's a race! I had not realized the size, Git clone is still chugging away!

**Comment by WiseNerd** [comment]
@blobgo well my macbook's limited ddr2 memory would be neutered by sanitizing that entire thing, I fixed a small part mostly out of curiosity. But was hoping to save somebody some time nonetheless :)

**Comment by iancnorden** [comment]
De-dupes still running.

**Comment by berzerk0** [comment]
Initial De-Dupes (up to ~30 Million Non-Spec and WPA) are done, looks like I can't do the big ones in parallel

**Comment by iancnorden** [comment]
Chewing on the folder with Top2Bil*, @ *aco*, 960 total lines, forgot to list before starting to tell you where I'm at.

If curious, thanks to https://github.com/ltdenard ...

`for f in `ls -lha .| tail -n+4 | awk '{print $10}'`; do sort -u ${f} > /tmp/tmp1 && mv /tmp/tmp1 ./${f}; done;`

**Comment by palexhorse** [comment]
Can all unique combinations be put into a new file, or do you just want the duplicates removed?

**Comment by berzerk0** [comment]
For Rev 1.1 we aim to just remove the duplicates while otherwise preserving order.
The "duplicates" are likely illusory, where there probably are invisible newline characters splitting them up.
This has some effect on overall accuracy once they have been removed.

Rev 2.0 will have the newlines weeded out at the source, so this problem will not carry over.

**Comment by berzerk0** [comment]
De-Duped Rev 1.1 is live now, but does not contain the largest files.

Rev 1.2 will, in torrents with compression.

Closing this in light of the release of 1.1 and the impending release of 1.2
