### ISSUE TITLE
Note/warn about size

### ISSUE THREAD

**Issue by blobgo** [berzerk0/Probable-Wordlists#3]
You should state the size of the whole repo in the Readme, so people are not surprised when cloning it… :smile:

**Comment by russellvt** [comment]
You're probably looking for [this URL](https://api.github.com/repos/berzerk0/Probable-Wordlists), which is part of the git API, -- which should be available for any repository you have access to read (ie. just fix the URI, applicably).

**Comment by russellvt** [comment]
Perhaps more clearly, where $1 is the github user / organization, and $2 is the github username:

`curl https://api.github.com/repos/$1/$2 | grep size`

**Comment by wezmaster** [comment]
I have been trying to download this via browser (zip) , also trying to clone it (github desktop) but so far it has not been successful despite multiple attempts. Wondering if you could post size of this .. would appreciate if this could be available via torrent.

**Comment by berzerk0** [comment]
Posted about size in README.md - warning is visible above logo.

Zipping/Torrentization in process

**Comment by nurupo** [comment]
Besides .zip, it might be useful to provide an archive that uses LZMA/LZMA2 compression, as it should produse even smaller file. .xz archive would be the best option for that, with .7z being the second best option if for some reason you can'take do .xz.

**Comment by berzerk0** [comment]
Using 7zip, I've been able to create .zips with LZMA compression - getting about 25% compression ratio. and it opens on most operating systems without much trouble

**Comment by nurupo** [comment]
Ok, I see, it's an LZMA .zip. That should be fine then. .zip archives are generally compressed with DEFLATE compression algorithm, so that's what I have assumed it was.

**Comment by berzerk0** [comment]
I'll make that more obvious, because that's a reasonable assumption
