### ISSUE TITLE
So is this all the passwords, or only those that showed up in the analysis twice? 

### ISSUE THREAD

**Issue by morangeman** [berzerk0/Probable-Wordlists#31]
Hello,

Is this all individual passwords you found or all of those that only showed across the files twice?

If so, what about other passwords that were unique to only one list (only 1 person had that password), or words from books, Wikipedia, Gutenberg etc...

Perhaps I'm just misunderstanding but would like this clarified.... 

Thanks for your work on this project!

**Comment by morangeman** [comment]
Also as a side note, have you had a chance to look into the December 1.4 billion leak? I'm guessing most likely yes. I've read it's mostly email addresses and old lists anyway but curious to know if there are new uniques.

**Comment by berzerk0** [comment]
1. This is all the passwords that I found at least TWICE. Of the original corpus, 1/3 of the passwords were used more than once. 2/3 were only used one time. 

While it may be useful to have a giant alphabetized password list, that's not the intent of this project. I can'tgo claiming a password was "likely to be used" if it was only documented once.


2. From what I can tell, the 1.4 Billion leak is comprised of sources that will be included in V2.

**Comment by morangeman** [comment]
Thanks for the response, much appreciated clarification. Are you intending on releasing the other 2/3 in a separate list somewhere or are these passwords already located in another project? Always best to have the most complete wordlists for reference as people are creatures of habit.

**Comment by berzerk0** [comment]
I haven't prepared or released them anywhere else. Distributing lists that large might be feasible for a company, but it's not feasible for me to do at this time.

The sources for these lists are not difficult to to come by, however. I found all of the lists simply via google search. You can create your own super large wordlist pretty easily - and if you don't care too much about optimization, there won't be as much sorting time.
