### ISSUE TITLE
SecLists Integration

### ISSUE THREAD

**Issue by danielmiessler** [berzerk0/Probable-Wordlists#38]
Great work here!

We'd like to include the content in SecLists. Is that ok with you?

**Comment by berzerk0** [comment]
I'd be honored!
Seclists is/was a major source of inspiration/materials for this project.

I submitted some already in [https://github.com/danielmiessler/SecLists/commit/4d6d6dcee29930587b26cee84fcd90e13eb38510](this approved pull request,) but just the smaller lists - I didn't want to weigh you down too much.

**Comment by danielmiessler** [comment]
Awesome! Thanks!
