### ISSUE TITLE
all .txt password files dont have anything separating the passwords

### ISSUE THREAD

**Issue by migel210** [berzerk0/Probable-Wordlists#42]
If the passwords aren't separated by any characters, how is a program supposed to know when one password ends and another starts?

**Comment by roycewilliams** [comment]
Are you opening them with [an older version of Notepad](https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/)?

The lines are separated by Unix-style newlines, not DOS/Windows newlines.

**Comment by berzerk0** [comment]
@roycewilliams is correct.
The lines are separated by UNIX newlines - \n.

Programs like notepad++ displays them.


Marking as closed.
