### ISSUE TITLE
Passwords without spaces

### ISSUE THREAD

**Issue by FrancoSmit** [berzerk0/Probable-Wordlists#43]
Hi I'm new to all of this and I'm using Kali Linux.
I'm just downloaded these word-lists and opened some of them and I saw that there aren't any spaces between passwords, how can I fix this without manually adding spaces ?
Or is there no need for spaces when doing a dictionary attack ?

I do this for research purposes only of course.

**Comment by ba0f3** [comment]
https://github.com/berzerk0/Probable-Wordlists/issues/42
