### ISSUE TITLE
Are passwords for the same mail address deduplicated? 

### ISSUE THREAD

**Issue by domenukk** [berzerk0/Probable-Wordlists#49]
Looking through recent leaks, I found `mail:password` combos that are contained particularly often.
This, however, does not indicate it would be more commonly used. It should still count as a single occurrence.
Is this taken into account?

**Comment by berzerk0** [comment]
Yes.

In revisions 1 and 2, a password's popularity is determined based on the number of source files it appeared in, not how many times it appeared in each file. Each source file was stripped of all non-password information (as much as possible), and then had duplicates removed.
