### ISSUE TITLE
Corrupted torrent files?

### ISSUE THREAD

**Issue by cz2137** [berzerk0/Probable-Wordlists#52]
All torrent clients I've tried tells me that torrent files are malformed.
Tried: every torrent file in downloads, Clients: KTorrent, Transmission,qBittorrent.

Error message:

> An error occurred while loading https://github.com/berzerk0/Probable-Wordlists/blob/master/Real-Passwords/WPA-Length/WPA-Length-Rev-2-Torrents/ProbWL-v2-Real-WPA-Passwords-targz.torrent:
Illegal token: 10

**Comment by berzerk0** [comment]
That's very odd.
I'm unable to produce the issue using qbitorrent or Deluge.

Is it still happening?
