### ISSUE TITLE
Recommend Merge with OWASP project

### ISSUE THREAD

**Issue by MikeDawg** [berzerk0/Probable-Wordlists#8]
Would the data you provide here be a good set to "give" (considering licensing is currently unknown), to the OWASP SecLists project?

https://github.com/danielmiessler/SecLists

https://www.owasp.org/index.php/Projects/OWASP_SecLists_Project

**Comment by MikeDawg** [comment]
I see that this password list was pulled from the OWASP SecLists, after I misread what I saw in the README. 

Still thinking though, could this re-formatted data go back into SecLists, in its form that you have here on this repo?

**Comment by berzerk0** [comment]
It probably would be - but if so, I'll wait until Rev 1.1 at LEAST.

**Comment by berzerk0** [comment]
I think I'm going to keep them separate - I'll drop them a line and see if it would be worth adding some of the files.
